// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"
)

var Columns = struct {
	Stat struct {
		ID, UserID, Period, PeriodStart, PeriodEnd, TotalSeconds, DailyAverageSeconds, FetchedAt string

		User string
	}
	User struct {
		ID, Username, WakatimeLogin, WakatimeToken, StatusID, CreatedAt, LastSyncedAt, LastSyncError string
	}
}{
	Stat: struct {
		ID, UserID, Period, PeriodStart, PeriodEnd, TotalSeconds, DailyAverageSeconds, FetchedAt string

		User string
	}{
		ID:                  "statId",
		UserID:              "userId",
		Period:              "period",
		PeriodStart:         "periodStart",
		PeriodEnd:           "periodEnd",
		TotalSeconds:        "totalSeconds",
		DailyAverageSeconds: "dailyAverageSeconds",
		FetchedAt:           "fetchedAt",

		User: "User",
	},
	User: struct {
		ID, Username, WakatimeLogin, WakatimeToken, StatusID, CreatedAt, LastSyncedAt, LastSyncError string
	}{
		ID:            "userId",
		Username:      "username",
		WakatimeLogin: "wakatimeLogin",
		WakatimeToken: "wakatimeToken",
		StatusID:      "statusId",
		CreatedAt:     "createdAt",
		LastSyncedAt:  "lastSyncedAt",
		LastSyncError: "lastSyncError",
	},
}

var Tables = struct {
	Stat struct {
		Name, Alias string
	}
	User struct {
		Name, Alias string
	}
}{
	Stat: struct {
		Name, Alias string
	}{
		Name:  "stats",
		Alias: "t",
	},
	User: struct {
		Name, Alias string
	}{
		Name:  "users",
		Alias: "t",
	},
}

type Stat struct {
	tableName struct{} `pg:"stats,alias:t,discard_unknown_columns"`

	ID                  int       `pg:"statId,pk"`
	UserID              int       `pg:"userId,use_zero"`
	Period              string    `pg:"period,use_zero"`
	PeriodStart         time.Time `pg:"periodStart,use_zero"`
	PeriodEnd           time.Time `pg:"periodEnd,use_zero"`
	TotalSeconds        int64     `pg:"totalSeconds,use_zero"`
	DailyAverageSeconds int       `pg:"dailyAverageSeconds,use_zero"`
	FetchedAt           time.Time `pg:"fetchedAt,use_zero"`

	User *User `pg:"fk:userId"`
}

type User struct {
	tableName struct{} `pg:"users,alias:t,discard_unknown_columns"`

	ID            int        `pg:"userId,pk"`
	Username      string     `pg:"username,use_zero"`
	WakatimeLogin string     `pg:"wakatimeLogin,use_zero"`
	WakatimeToken []byte     `pg:"wakatimeToken,use_zero"`
	StatusID      int        `pg:"statusId,use_zero"`
	CreatedAt     time.Time  `pg:"createdAt,use_zero"`
	LastSyncedAt  *time.Time `pg:"lastSyncedAt"`
	LastSyncError *string    `pg:"lastSyncError"`
}
