// Code generated by zenrpc v2.3.1; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	WakaTimeService struct{ Register, GetTop string }
}{
	WakaTimeService: struct{ Register, GetTop string }{
		Register: "register",
		GetTop:   "gettop",
	},
}

func (WakaTimeService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Register": {
				Parameters: []smd.JSONSchema{
					{
						Name: "username",
						Type: smd.String,
					},
					{
						Name: "secretKey",
						Type: smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Optional: true,
					Type:     smd.Object,
					TypeName: "RegisterResult",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "username",
							Type: smd.String,
						},
						{
							Name: "status",
							Type: smd.String,
						},
					},
				},
			},
			"GetTop": {
				Parameters: []smd.JSONSchema{
					{
						Name: "period",
						Type: smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Optional: true,
					Type:     smd.Object,
					TypeName: "TopResult",
					Properties: smd.PropertyList{
						{
							Name: "period",
							Type: smd.String,
						},
						{
							Name: "periodStart",
							Type: smd.String,
						},
						{
							Name: "periodEnd",
							Type: smd.String,
						},
						{
							Name: "totalSeconds",
							Type: smd.Integer,
						},
						{
							Name: "items",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/TopItem",
							},
						},
						{
							Name: "fetchedAt",
							Type: smd.String,
						},
					},
					Definitions: map[string]smd.Definition{
						"TopItem": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "rank",
									Type: smd.Integer,
								},
								{
									Name: "username",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s WakaTimeService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.WakaTimeService.Register:
		var args = struct {
			Username     string `json:"username"`
			SecretApiKey string `json:"secretApiKey"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"username", "secretKey"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Register(ctx, args.Username, args.SecretApiKey))

	case RPC.WakaTimeService.GetTop:
		var args = struct {
			Period string `json:"period"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"period"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.GetTop(ctx, args.Period))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
