CREATE TABLE "users" (
	"userId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"username" text NOT NULL,
	"wakatimeLogin" text NOT NULL,
	"wakatimeToken" bytea NOT NULL,
	"statusId" integer NOT NULL,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"lastSyncedAt" timestamptz,
	"lastSyncError" text,
	CONSTRAINT "pk_users" PRIMARY KEY("userId")
);

CREATE TABLE "stats" (
	"statId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"userId" integer NOT NULL,
	"period" text NOT NULL,
	"periodStart" date NOT NULL,
	"periodEnd" date NOT NULL,
	"totalSeconds" bigint NOT NULL,
	"dailyAverageSeconds" integer NOT NULL,
	"fetchedAt" timestamptz NOT NULL,
	CONSTRAINT "pk_stats" PRIMARY KEY("statId")
);

CREATE TABLE "statuses" (
	"statusId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"alias" text NOT NULL,
	"title" text NOT NULL,
	CONSTRAINT "pk_statuses" PRIMARY KEY("statusId")
);

CREATE UNIQUE INDEX "uq_statuses_alias" ON "statuses" (
	"alias"
);

CREATE UNIQUE INDEX "uq_stats_period" ON "stats" (
	"period",
	"userId",
	"periodEnd"
);

CREATE INDEX "ix_stats_user_id" ON "stats" (
	"userId",
	"fetchedAt" DESC
);

CREATE UNIQUE INDEX "uq_users_wakatime_login" ON "users" (
	"wakatimeLogin"
);

CREATE INDEX "ix_users_status_id" ON "users" (
	"statusId"
);

ALTER TABLE "users" ADD CONSTRAINT "fk_users_1" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "stats" ADD CONSTRAINT "fk_stat_1" FOREIGN KEY ("userId")
	REFERENCES "users"("userId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

