CREATE TABLE "users" (
	"id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"username" text NOT NULL,
	"wakatime_login" text NOT NULL,
	"wakatime_token" bytea NOT NULL,
	"status_id" integer NOT NULL,
	"created_at" timestamptz NOT NULL DEFAULT now(),
	"last_synced_at" timestamptz,
	"last_sync_error" text,
	CONSTRAINT "pk_users" PRIMARY KEY("id")
);

CREATE TABLE "stats" (
	"id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"user_id" int NOT NULL,
	"period" text NOT NULL,
	"period_start" date NOT NULL,
	"period_end" date NOT NULL,
	"total_seconds" bigint NOT NULL,
	"daily_average_seconds" integer NOT NULL,
	"fetched_at" timestamptz NOT NULL,
	CONSTRAINT "pk_stats" PRIMARY KEY("id")
);

CREATE TABLE "statuses" (
	"id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"alias" text NOT NULL,
	"title" text NOT NULL,
	CONSTRAINT "pk_statuses" PRIMARY KEY("id")
);

CREATE UNIQUE INDEX "uq_stats_period" ON "stats" (
	"period",
	"user_id",
	"period_end"
);

CREATE INDEX "ix_stats_user_id" ON "stats" (
	"user_id",
	"fetched_at" DESC
);

CREATE UNIQUE INDEX "uq_statuses_alias" ON "statuses" (
	"alias"
);

CREATE UNIQUE INDEX "uq_users_wakatime_login" ON "users" (
	"wakatime_login"
);

CREATE INDEX "ix_users_status_id" ON "users" (
	"status_id"
);

ALTER TABLE "users" ADD CONSTRAINT "fk_users_1" FOREIGN KEY ("status_id")
	REFERENCES "statuses"("id")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "stats" ADD CONSTRAINT "fk_stat_1" FOREIGN KEY ("user_id")
	REFERENCES "users"("id")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

